INSERT INTO `backend_db`.`USER`
VALUES (1,
        "John Doe");

INSERT INTO `backend_db`.`TRANSACTION`
VALUES ("2ed1f4af-70a8-4b06-9fff-4f1b620ccca7",
        1.1,
        "Autogenerated",
        "2020-01-01",
        1);
INSERT INTO `backend_db`.`TRANSACTION`
VALUES ("2ed1f4af-70a8-4b06-9fff-4f1b620cccaa",
        1.1,
        "Autogenerated",
        "2020-05-30",
        1);
INSERT INTO `backend_db`.`TRANSACTION`
VALUES ("2ed1f4af-70a8-4b06-9fff-4f1b620cccab",
        1.1,
        "Autogenerated",
        "2020-06-01",
        1);
INSERT INTO `backend_db`.`TRANSACTION`
VALUES ("2ed1f4af-70a8-4b06-9fff-4f1b620cccac",
        1.1,
        "Autogenerated",
        "2020-01-08",
        1);
